title: サイバーセキュリティ
summary: サイバーセキュリティの基礎を事例とともに学ぶ
topics: ["サイバーセキュリティ"]
published: true
price: 200
chapters:
  - communication-path-security
  - vulenerability
  - botnet
  - botnet-attack
  - intrusion-detection