title: サイバーセキュリティ
summary: サイバーセキュリティの基礎を事例とともに学ぶ
topics: ["サイバーセキュリティ"]
published: true
price: 200
chapters:
  - communication-path-security
  - vulnerability
  - botnet
  - botnet-attack
  - intrusion-detection
  - dns-security
  - malware-detection
  - access-control
  - vulnerability-management